### ISSUE TITLE
URLs dead - skinhub dysfunctional

### ISSUE THREAD

**Issue by ryancranie** [ryancranie/skinhub#4]
Ran that merge and now some urls redirect to the wrong url like: b/woal/raw//player/lifeline/funorange%20edit.osk

instead of

b/woal/raw/tyfh/player/lifeline/funorange%20edit.osk

tyfh was skipped out on a few URLs I guess, might be something greater too tired to think abt it rn.

**Comment by cuttinglanes** [comment]
sorry for missing a few! here's a quick little list of some that i found

toke charlotte

cookie-_LUCIANO image link

all of the images in lystia's skinhub lack links, hyperlinks are fine

tko reused hyperlink is wrong

all of shene's is wrong

some of lifelines are missing branch in link

ypan edit on aleph's skinhub is missing branch in link

asterllia lenathea image link is wrong

**Comment by ryancranie** [comment]
I'd rather revert the merge and try run the script to change all the urls again, instead of nitpicking everything, if you can 100% confirm your branch has all correct urls I will merge again.
